version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk	      
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
